#!/usr/bin/env node
// Generate a copyright-free SlowROM instruction stream and a Mesen2 trace.

import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const [outArg, samplesArg = "5000"] = process.argv.slice(2);
if (!outArg) {
  console.error("Usage: node test/mesen/dram_refresh_probe.mjs <out-dir> [samples]");
  process.exit(2);
}
const samples = Number(samplesArg);
if (!Number.isInteger(samples) || samples < 2 || samples > 100000) throw new Error("samples must be 2..100000");
const outDir = resolve(outArg);
mkdirSync(outDir, { recursive: true });
const romPath = resolve(outDir, "dram-refresh.sfc");
const luaPath = resolve(outDir, "dram-refresh.lua");
const tracePath = resolve(outDir, "dram-refresh.tsv");

const rom = Buffer.alloc(0x8000, 0xff);
rom.set([
  0x78, 0xd8, 0xa2, 0xff, 0x9a, 0xa9, 0x00,
  0x8d, 0x00, 0x42, 0x8d, 0x0c, 0x42, 0x4c, 0x00, 0x81,
], 0);
for (let i = 0; i < 32; i++) rom.set([0xa9, i], 0x100 + i * 2); // LDA #imm
rom.set([0x4c, 0x00, 0x81], 0x140); // JMP $8100
rom.write("DRAM REFRESH PROBE  ", 0x7fc0, "ascii");
rom[0x7fd5] = 0x20; // LoROM, SlowROM
rom[0x7fd6] = 0x00; // ROM only
rom[0x7fd7] = 0x08; // 32 KiB
rom[0x7fd8] = 0x00; // no SRAM
rom[0x7fd9] = 0x01; // NTSC
rom[0x7fda] = 0x33;
rom[0x7ffc] = 0x00; rom[0x7ffd] = 0x80;
writeFileSync(romPath, rom);

const luaString = value => JSON.stringify(value);
const lua = `-- generated by test/mesen/dram_refresh_probe.mjs
local output = assert(io.open(${luaString(tracePath)}, "w"))
output:write("address\\tmaster\\tscanline\\thclock\\n")
local samples = 0
local function onExec(address)
  local state = emu.getState()
  output:write(string.format("%06x\\t%d\\t%d\\t%d\\n", address,
    state["masterClock"], state["ppu.scanline"], state["memoryManager.hClock"]))
  samples = samples + 1
  if samples >= ${samples} then output:close(); emu.stop(0) end
end
emu.addMemoryCallback(onExec, emu.callbackType.exec, 0x008100, 0x008140, emu.cpuType.snes, emu.memType.snesMemory)
`;
writeFileSync(luaPath, lua);
console.log(`wrote ${romPath}`);
console.log(`wrote ${luaPath}`);
console.log(`trace output: ${tracePath}`);
