#!/usr/bin/env node
// Generate a copyright-free LoROM and Mesen2 Lua trace for $4212 access-time
// sampling. No SMW bytes are embedded: the small wait routine is assembled
// directly from the instruction sequence documented in the source note.

import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const [outArg, yArg = "31", callsArg = "160"] = process.argv.slice(2);
if (!outArg) {
  console.error("Usage: node test/mesen/hvbjoy_access_probe.mjs <out-dir> [initial-y] [calls]");
  process.exit(2);
}
const initialY = Number(yArg);
const calls = Number(callsArg);
if (!Number.isInteger(initialY) || initialY < 1 || initialY > 255) throw new Error("initial-y must be 1..255");
if (!Number.isInteger(calls) || calls < 1 || calls > 10000) throw new Error("calls must be 1..10000");
const outDir = resolve(outArg);
mkdirSync(outDir, { recursive: true });
const romPath = resolve(outDir, `hvbjoy-y${initialY}.sfc`);
const luaPath = resolve(outDir, `hvbjoy-y${initialY}.lua`);
const tracePath = resolve(outDir, `hvbjoy-y${initialY}.tsv`);

const rom = Buffer.alloc(0x8000, 0xff);
const setupAndSweep = [
  0x78, 0xd8, 0xa2, 0xff, 0x9a, 0xa9, 0x00, 0x8d, 0x00, 0x42,
  0x8d, 0x0c, 0x42, 0x64, 0x00, 0xa6, 0x00, 0xf0, 0x03, 0xca,
  0xd0, 0xfd, 0xa0, initialY, 0x20, 0x30, 0x80, 0xe6, 0x00, 0x80, 0xf0,
];
rom.set(setupAndSweep, 0);
rom.set([0xa0, 0x20], 0x2e); // LDY #$20 on the leave-HBlank path.
rom.set([
  0x2c, 0x12, 0x42, // BIT $4212
  0x70, 0xf9, // BVS $802E
  0x2c, 0x12, 0x42, // BIT $4212
  0x50, 0xfb, // BVC $8035
  0x88, // DEY
  0xd0, 0xfd, // BNE $803A
  0x60, // RTS
], 0x30);
rom.write("HVBJOY ACCESS PROBE  ", 0x7fc0, "ascii");
rom[0x7fd5] = 0x20; // LoROM, SlowROM
rom[0x7fd6] = 0x00; // ROM only
rom[0x7fd7] = 0x08; // 32 KiB
rom[0x7fd8] = 0x00; // no SRAM
rom[0x7fd9] = 0x01; // NTSC
rom[0x7fda] = 0x33;
rom[0x7ffc] = 0x00; rom[0x7ffd] = 0x80;
writeFileSync(romPath, rom);

const luaString = value => JSON.stringify(value);
const lua = `-- generated by test/mesen/hvbjoy_access_probe.mjs
local output = assert(io.open(${luaString(tracePath)}, "w"))
output:write("kind\\tcall\\taddress\\tvalue\\tmaster\\tscanline\\thclock\\tresidual\\tbranch_from\\n")
local call = 0
local pendingBranch = 0
local lastReadValue = 0
local function stamp(kind, address, value, branchFrom)
  local state = emu.getState()
  local hclock = state["memoryManager.hClock"]
  output:write(string.format("%s\\t%d\\t%06x\\t%02x\\t%d\\t%d\\t%d\\t%d\\t%06x\\n",
    kind, call, address, value or 0, state["masterClock"], state["ppu.scanline"],
    hclock, hclock % 4, branchFrom or 0))
end
local function onExec(address, value)
  if pendingBranch ~= 0 then
    stamp("next", address, value, pendingBranch)
    pendingBranch = 0
  end
  if address == 0x008018 then call = call + 1; stamp("call", address, value) end
  if address == 0x008030 or address == 0x008035 then stamp("bit-start", address, value) end
  if address == 0x008033 or address == 0x008038 then
    stamp("branch", address, lastReadValue)
    pendingBranch = address
  end
  if address == 0x00801b then
    stamp("return", address, value)
    if call >= ${calls} then output:close(); emu.stop(0) end
  end
end
local function onRead(address, value) lastReadValue = value; stamp("read", address, value) end
emu.addMemoryCallback(onExec, emu.callbackType.exec, 0x008000, 0x00803d, emu.cpuType.snes, emu.memType.snesMemory)
emu.addMemoryCallback(onRead, emu.callbackType.read, 0x004212, 0x004212, emu.cpuType.snes, emu.memType.snesMemory)
`;
writeFileSync(luaPath, lua);
console.log(`wrote ${romPath}`);
console.log(`wrote ${luaPath}`);
console.log(`trace output: ${tracePath}`);
