#!/usr/bin/env python3
"""Generate a Mesen2 --testrunner Lua script that plays a .zmov movie and
saves a screenshot at a target frame.

The pixel-level counterpart of make_trace_script.py: where that script
cross-validates RAM state (SMW physics), this one cross-validates the
rendered image - built for Super Mario Kart's Mode 7 track, where the
interesting state (the DSP-1-computed perspective matrix) is easiest to
compare as a picture.

Usage:
  make_screenshot_script.py <movie.zmov> <shot_frame> <out.lua> <shot.png>

Run headless:
  ~/Repos/Mesen2/Mesen.app/Contents/MacOS/Mesen --testrunner <rom> <out.lua>

Note Mesen renders 512x478 (hi-res doubled) or 256x239 depending on
settings; compare after normalizing size. Requires the same one-time
Mesen settings as the trace harness (AllowIoOsAccess, Port1 controller).
"""

import sys
from make_trace_script import parse_zmov


def main():
    movie_path, shot_frame, out_path, shot_out = (
        sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4])
    frames = parse_zmov(movie_path)

    entries = []
    for i, buttons in enumerate(frames):
        if buttons:
            fields = ','.join(f'{b}=true' for b in sorted(buttons))
            entries.append(f'  [{i}]={{{fields}}},')

    lua = f"""-- generated by make_screenshot_script.py - do not edit
local movie = {{
{chr(10).join(entries)}
}}
local SHOT = {shot_frame}
local frameIndex = 0

local function onPoll()
  local state = {{ a=false, b=false, x=false, y=false, l=false, r=false,
                   up=false, down=false, left=false, right=false,
                   select=false, start=false }}
  local m = movie[frameIndex]
  if m then
    for k, v in pairs(m) do state[k] = v end
  end
  emu.setInput(state, 0)
end

local function onEndFrame()
  frameIndex = frameIndex + 1
  if frameIndex == SHOT then
    local png = emu.takeScreenshot()
    local f = io.open("{shot_out}", "wb")
    f:write(png)
    f:close()
    emu.stop(0)
  end
end

emu.addEventCallback(onPoll, emu.eventType.inputPolled)
emu.addEventCallback(onEndFrame, emu.eventType.endFrame)
"""
    with open(out_path, 'w') as f:
        f.write(lua)
    print(f"wrote {out_path}: {len(frames)} movie frames, screenshot at {shot_frame}")


if __name__ == '__main__':
    main()
