#!/usr/bin/env python3
"""Generate a Mesen2 --testrunner Lua script that plays a .zmov movie and
logs a per-frame state trace.

Mesen2 is the third-vote emulator for cross-validation (see
CPU-VECTORS-NOTES.md and the ZuperWorld plan): the same movie file drives
zupernes, the ZuperWorld engine, and Mesen2, and their traces are compared
frame by frame. The movie is baked INTO the generated Lua (no io library
needed inside Mesen's sandbox); the trace is emitted via emu.log lines
prefixed with "T\t", which the runner script extracts from stdout.

Requires Mesen's ScriptAllowIoOsAccess setting (the harness runner sets
it in Mesen.app/Contents/MacOS/settings.json) so Lua can write the trace
file directly - emu.log does not reach stdout in testrunner mode.

Usage:
  make_trace_script.py <movie.zmov> <total_frames> <out.lua> <trace_out>

Run headless (no window):
  ~/Repos/Mesen2/Mesen.app/Contents/MacOS/Mesen --testrunner <rom> <out.lua>

Trace columns match the ZuperWorld oracle:
  frame mode state pow dir air water xspd yspd x y
"""

import sys

BUTTON_NAMES = {
    'B': 'b', 'Y': 'y', 's': 'select', 'S': 'start',
    'U': 'up', 'D': 'down', 'L': 'left', 'R': 'right',
    'A': 'a', 'X': 'x', 'l': 'l', 'r': 'r',
}


def parse_zmov(path):
    frames = []
    with open(path) as f:
        lines = f.read().split('\n')
    # Drop the single trailing empty segment from a final newline
    if lines and lines[-1] == '':
        lines = lines[:-1]
    for line in lines:
        line = line.strip()
        if line.startswith('#'):
            continue
        buttons = set()
        for c in line:
            if c == '.':
                continue
            buttons.add(BUTTON_NAMES[c])
        frames.append(buttons)
    return frames


def main():
    movie_path, total_frames, out_path, trace_out = sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4]
    frames = parse_zmov(movie_path)

    # Sparse movie table: only frames with input
    entries = []
    for i, buttons in enumerate(frames):
        if buttons:
            fields = ','.join(f'{b}=true' for b in sorted(buttons))
            entries.append(f'  [{i}]={{{fields}}},')

    lua = f"""-- generated by make_trace_script.py - do not edit
local movie = {{
{chr(10).join(entries)}
}}
local TOTAL = {total_frames}
local frameIndex = 0
local trace = io.open("{trace_out}", "w")
trace:write("# frame\\tmode\\tstate\\tpow\\tdir\\tair\\twater\\txspd\\tyspd\\tx\\ty\\n")

local function onPoll()
  local state = {{ a=false, b=false, x=false, y=false, l=false, r=false,
                   up=false, down=false, left=false, right=false,
                   select=false, start=false }}
  local m = movie[frameIndex]
  if m then
    for k, v in pairs(m) do state[k] = v end
  end
  emu.setInput(state, 0)
end

local function onEndFrame()
  local function r(a) return emu.read(a, emu.memType.snesWorkRam, false) end
  local x = r(0x95) * 256 + r(0x94)
  local y = r(0x97) * 256 + r(0x96)
  trace:write(string.format("%d\\t%02x\\t%02x\\t%02x\\t%02x\\t%02x\\t%02x\\t%02x\\t%02x\\t%04x\\t%04x\\t%02x\\n",
    frameIndex, r(0x100), r(0x71), r(0x19), r(0x76), r(0x72), r(0x75),
    r(0x7b), r(0x7d), x, y, r(0x13)))
  frameIndex = frameIndex + 1
  if frameIndex >= TOTAL then
    trace:close()
    emu.stop(0)
  end
end

emu.addEventCallback(onPoll, emu.eventType.inputPolled)
emu.addEventCallback(onEndFrame, emu.eventType.endFrame)
"""
    with open(out_path, 'w') as f:
        f.write(lua)
    print(f"wrote {out_path}: {len(frames)} movie frames, tracing {total_frames}")


if __name__ == '__main__':
    main()
